### ISSUE TITLE
Continue passively learning from channel messages

### ISSUE THREAD

**Issue by Cabji** [xitiomet/irc-gpt-bot#2]
Is it possible to make the bot passively learn simply by it watching/processing information that is sent in an IRC channel? This would be really cool.

**Comment by xitiomet** [comment]
Sadly not possible yet, the application is not doing any of the AI legwork, everything is offloaded to chatGPT's API. (which doesn't have a memory at all)

You can increase how much of the chat history is provided for context on every request by increasing the "contextDepth" in the config file. However this will increase the cost of doing business with OpenAI since they charge based on the number of tokens (words) sent with each request.
